name: ai-course
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - jupyter-book
  # - ghp-import
  # - seaborn
  # - matplotlib
  # - numpy
  # #- git+https://github.com/pantelis-classes/PRML.git#egg=prml
  # - plotly
  - ipywidgets
  # - dash
  # - pandas
  # - jupyter
  # - jupyterlab
  # # - jupyter-dash
  # # - tensorflow
  # - pyppeteer
  - pip: 
    - sphinxcontrib-svg2pdfconverter
    - sphinxcontrib-youtube
    - sphinx_inline_tabs
    - kaleido
    - sphinx_click
    - sphinx_inline_tabs
    - sphinxext.rediraffe
    - sphinx_proof
    - sphinx_examples
