# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Introduction to Artificial Intelligence
author: Pantelis Monogioudis, Ph.D
copyright                   : "2022"  # Copyright year to be placed in the footer
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  exclude_patterns: 
    - artificial_intelligence/handson-ml2/01_the_machine_learning_landscape.ipynb
    - artificial_intelligence/handson-ml2/02_end_to_end_machine_learning_project.ipynb
    - artificial_intelligence/handson-ml2/03_classification.ipynb
    - artificial_intelligence/handson-ml2/04_training_linear_models.ipynb
    - artificial_intelligence/handson-ml2/05_support_vector_machines.ipynb
    - artificial_intelligence/handson-ml2/06_decision_trees.ipynb
    - artificial_intelligence/handson-ml2/07_ensemble_learning_and_random_forests.ipynb
    - artificial_intelligence/handson-ml2/08_dimensionality_reduction.ipynb
    - artificial_intelligence/handson-ml2/18_reinforcement_learning.ipynb
    - artificial_intelligence/handson-ml2/*
    
only_build_toc_files: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: ai-book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - ai.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/pantelis/aiml-common # artificial-intelligence  # Online location of your book
  path_to_book: ''#lectures #artificial_intelligence/aiml-common  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  home_page_in_navbar: true
  use_edit_page_button: false
  use_issues_button: true
  use_repository_button: true
  use_download_button: true
  baseurl: https://pantelis.github.io/artificial-intelligence

launch_buttons:
  colab_url: "https://colab.research.google.com"

sphinx:
  recursive_update: false
  config:
    html_theme_options:
      use_download_button: true
      repository_url: https://github.com/pantelis/artificial-intelligence
      use_issues_button: true
      use_repository_button: true
      use_edit_page_button: false
  extra_extensions:
    - sphinxcontrib.youtube
    - sphinx_inline_tabs 

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - deflist
    - colon_fence
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution